/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecuperaSenha.java
 *
 * Created on Feb 8, 2013, 12:30:08 PM
 */
package productsfactory.view;

import productsfactory.useful.TelaUteis;

/**
 *
 * @author Daniel
 */
public class About extends javax.swing.JDialog {
     
     private static About jdialogRecuperaSenha = null;

    public static About getDialogAbout(){

        if (jdialogRecuperaSenha == null) {
            jdialogRecuperaSenha = new About(null, true);
        }
        return jdialogRecuperaSenha;
    }
    /** Creates new form RecuperaSenha */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializa();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEsqueceuSuaSenha = new interfacegrafica.dpa.panels.PanelTituloDPA("About");
        lblIconSistema = new interfacegrafica.dpa.labels.LabelDPA();
        lblSistema = new interfacegrafica.dpa.labels.LabelDPA();
        lblDesenvolvedor = new interfacegrafica.dpa.labels.LabelDPA();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");

        lblIconSistema.setForeground(new java.awt.Color(255, 0, 51));
        lblIconSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productsfactory/images/logo_report.jpg"))); // NOI18N
        lblIconSistema.setText("");

        lblSistema.setText("Sistema Products Factory Versão 1.0");

        lblDesenvolvedor.setText("Desenvolvido por: Daniel P. de Assis");

        javax.swing.GroupLayout pnlEsqueceuSuaSenhaLayout = new javax.swing.GroupLayout(pnlEsqueceuSuaSenha);
        pnlEsqueceuSuaSenha.setLayout(pnlEsqueceuSuaSenhaLayout);
        pnlEsqueceuSuaSenhaLayout.setHorizontalGroup(
            pnlEsqueceuSuaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEsqueceuSuaSenhaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlEsqueceuSuaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesenvolvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnlEsqueceuSuaSenhaLayout.setVerticalGroup(
            pnlEsqueceuSuaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEsqueceuSuaSenhaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblDesenvolvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(pnlEsqueceuSuaSenha, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfacegrafica.dpa.labels.LabelDPA lblDesenvolvedor;
    private interfacegrafica.dpa.labels.LabelDPA lblIconSistema;
    private interfacegrafica.dpa.labels.LabelDPA lblSistema;
    private interfacegrafica.dpa.panels.PanelTituloDPA pnlEsqueceuSuaSenha;
    // End of variables declaration//GEN-END:variables

    private void inicializa(){
        
        TelaUteis.locateOnScreen(this, 409, 300);
    }
}
