/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlteraSenhaView.java
 *
 * Created on 05/05/2013, 17:08:30
 */
package productsfactory.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import productsfactory.control.UsuarioControl;
import productsfactory.model.Usuario;
import productsfactory.useful.MailUteis;
import productsfactory.useful.TelaUteis;

/**
 *
 * @author Daniel
 */
public class AlteraSenhaView extends javax.swing.JDialog {

    private static Usuario user = null;
    private static AlteraSenhaView jDialogAlteraSenha = null;
    /**
     * Singleton, recupera a instância do formulário
     * 
     * @param janela
     * @param usuario
     * @return instância do Formulário
     */
    public static AlteraSenhaView getDialogAlteraSenha(java.awt.Frame janela, Usuario usuario) {

        if (jDialogAlteraSenha == null) {
            jDialogAlteraSenha = new AlteraSenhaView(janela, true, usuario);
        }
        return jDialogAlteraSenha;
    }

    /** Creates new form AlteraSenhaView */
    public AlteraSenhaView(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        initComponents();
        user = usuario;
        inicializa();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAlterarSenha = new interfacegrafica.dpa.panels.PanelDPA();
        lblHeadAlteraSenha = new interfacegrafica.dpa.labels.LabelDPA();
        lblUsuario = new interfacegrafica.dpa.labels.LabelDPA();
        lblSenhaAtual = new interfacegrafica.dpa.labels.LabelDPA();
        lblNovaSenha = new interfacegrafica.dpa.labels.LabelDPA();
        tfUsuario = new interfacegrafica.dpa.textfield.TextFieldDPA();
        pfSenhaAtual = new interfacegrafica.dpa.password.PasswordFieldDPA();
        pfNovaSenha = new interfacegrafica.dpa.password.PasswordFieldDPA();
        btnAlterarSenha = new interfacegrafica.dpa.buttons.ButtonSimplesDPA();
        btnCancelar = new interfacegrafica.dpa.buttons.ButtonSimplesDPA();
        btnHelp = new interfacegrafica.dpa.buttons.ButtonSimplesDPA();
        lblObrigatorioUsuario = new javax.swing.JLabel();
        lblObrigatorioUsuario1 = new javax.swing.JLabel();
        lblObrigatorioUsuario2 = new javax.swing.JLabel();
        lblCamposObrigatorios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Senha");

        lblHeadAlteraSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productsfactory/images/alterasenha.jpg"))); // NOI18N
        lblHeadAlteraSenha.setText("");

        lblUsuario.setText("Nome Usuário:");

        lblSenhaAtual.setText("Senha Atual:");

        lblNovaSenha.setText("Nova Senha:");

        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Canecelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productsfactory/images/help.png"))); // NOI18N
        btnHelp.setText("");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblObrigatorioUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblObrigatorioUsuario.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorioUsuario.setText("*");

        lblObrigatorioUsuario1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblObrigatorioUsuario1.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorioUsuario1.setText("*");

        lblObrigatorioUsuario2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblObrigatorioUsuario2.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorioUsuario2.setText("*");

        lblCamposObrigatorios.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblCamposObrigatorios.setForeground(new java.awt.Color(255, 0, 0));
        lblCamposObrigatorios.setText("*  Campos Obrigatórios");

        javax.swing.GroupLayout pnlAlterarSenhaLayout = new javax.swing.GroupLayout(pnlAlterarSenha);
        pnlAlterarSenha.setLayout(pnlAlterarSenhaLayout);
        pnlAlterarSenhaLayout.setHorizontalGroup(
            pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                        .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAlterarSenhaLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(lblHeadAlteraSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlterarSenhaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCamposObrigatorios)))
                .addContainerGap())
            .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pfNovaSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pfSenhaAtual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObrigatorioUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObrigatorioUsuario1)
                    .addComponent(lblObrigatorioUsuario))
                .addGap(50, 50, 50))
        );
        pnlAlterarSenhaLayout.setVerticalGroup(
            pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadAlteraSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                        .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                        .addComponent(lblObrigatorioUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObrigatorioUsuario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObrigatorioUsuario2))
                .addGap(36, 36, 36)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(lblCamposObrigatorios)
                .addContainerGap())
        );

        getContentPane().add(pnlAlterarSenha, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
// TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Para alterar sua senha digite sua antiga senha, a nova senha que deseja incluir e click no botão Alterar Senha.\n\r"
            + "Um email com a sua nova senha será enviado para o email cadastrado junto com sua conta de usuário.\n\r"
            + "Sua senha é pessoal não revele a outras pessoas.\n\r", "Alterar Senha", 1);
}//GEN-LAST:event_btnHelpActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
    Usuario usuario = new Usuario();
    usuario.setNomeUsuario(user.getNomeUsuario());
    usuario.setSenhaUsuario(String.valueOf(this.pfSenhaAtual.getPassword()));

    if (validaCampos()) {
        try {
            if (UsuarioControl.verificarSenha(usuario)) {
                usuario.setSenhaUsuario(String.valueOf(this.pfNovaSenha.getPassword()));
                UsuarioControl usuarioControl = new UsuarioControl();
                if (usuarioControl.atualizarSenhaUsuario(usuario)) {
                    String emailUsuario = UsuarioControl.getUsuario(usuario).getEmailUsuario();
                    MailUteis.enviaEmailUsuario(emailUsuario, user.getNomeUsuario(), String.valueOf(this.pfNovaSenha.getPassword()));
                    EnviaEmailProgress enviaEmailProgress = new EnviaEmailProgress(this, true);
                    enviaEmailProgress.setVisible(true);
                    this.pfNovaSenha.setText("");
                    this.pfSenhaAtual.setText("");
                    JOptionPane.showMessageDialog(this, "Senha alterada com Sucesso.", "Altera Senha", 1);
                } else {
                    JOptionPane.showMessageDialog(this, "Senha não pode ser alterada.", "Altera Senha!", 2);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuário e senha não coincidem.", "Altera Senha!", 2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(AlteraSenhaView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}//GEN-LAST:event_btnAlterarSenhaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfacegrafica.dpa.buttons.ButtonSimplesDPA btnAlterarSenha;
    private interfacegrafica.dpa.buttons.ButtonSimplesDPA btnCancelar;
    private interfacegrafica.dpa.buttons.ButtonSimplesDPA btnHelp;
    private javax.swing.JLabel lblCamposObrigatorios;
    private interfacegrafica.dpa.labels.LabelDPA lblHeadAlteraSenha;
    private interfacegrafica.dpa.labels.LabelDPA lblNovaSenha;
    private javax.swing.JLabel lblObrigatorioUsuario;
    private javax.swing.JLabel lblObrigatorioUsuario1;
    private javax.swing.JLabel lblObrigatorioUsuario2;
    private interfacegrafica.dpa.labels.LabelDPA lblSenhaAtual;
    private interfacegrafica.dpa.labels.LabelDPA lblUsuario;
    private interfacegrafica.dpa.password.PasswordFieldDPA pfNovaSenha;
    private interfacegrafica.dpa.password.PasswordFieldDPA pfSenhaAtual;
    private interfacegrafica.dpa.panels.PanelDPA pnlAlterarSenha;
    private interfacegrafica.dpa.textfield.TextFieldDPA tfUsuario;
    // End of variables declaration//GEN-END:variables

    /**
     * Valida os campos necessários
     * para a alteração da senha
     * @return 
     */
    private boolean validaCampos() {

        if (this.tfUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome do usuário é Obrigatório", "Atenção!", 2);
            return false;
        } else if (String.valueOf(this.pfSenhaAtual.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Senha Atual é Obrigatória", "Atenção!", 2);
            return false;
        } else if (String.valueOf(this.pfNovaSenha.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nova Senha é Obrigatória", "Atenção!", 2);
            return false;
        }

        return true;
    }

    private void addWindowListener() {

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent evt) {
                System.gc();
                jDialogAlteraSenha = null;
            }
        });
    }

    /**
     * Faz as inicializações do Formulário
     */
    private void inicializa() {
        this.addWindowListener();
        TelaUteis.locateOnScreen(this, 540, 385);
        this.tfUsuario.setText(user.getNomeUsuario());
        this.tfUsuario.setEditable(false);

    }
}
