/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StateView.java
 *
 * Created on 18/05/2012, 20:17:34
 */
package productsfactory.view;


import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import productsfactory.model.BlOcParamModel;
import productsfactory.model.Fields;
import productsfactory.model.Offers;
import productsfactory.model.PerfilModel;
import productsfactory.model.Verifyer;
import productsfactory.useful.ArquivosUtil;
import productsfactory.useful.ConexaoOracle;
import productsfactory.useful.FieldsUtil;

/**
 *
 * @author Julio
 */
public class BlOcParamView extends javax.swing.JFrame {
    
    StringBuilder strLog = new StringBuilder();
    private static BlOcParamView jFramePerfil = null;
    
    /** Creates new form Menu */
    public BlOcParamView() {
        
    }
    
    
     public BlOcParamView(java.awt.Frame janela) {
        initComponents();
        //this.edtCodigo.setVisible(false);
        
       this.txtDescricao.setText("BSR -Novo Portfólio BL e Pacotes Adicionais");
       this.txtDlServiceCode.setText("10795");
       this.txtDlUpdateStamp.setText("4");
       this.txtOperatorID.setText("93277340");
       
       
     
       
       this.edtCodigo.setText("167000887\n"+
                                "167000889\n"+
                                "169000753\n"+
                                "169000952\n"+
                                "169000979\n"+
                                "169000991\n"+
                                "169001090\n"+
                                "169001154\n"+
                                "169001208\n"+
                                "169001235\n"+
                                "169001264\n");

       
       this.edtValores.setText("0.80\n"+
                            "0.90\n"+
                            "0.25\n"+
                            "0.31\n"+
                            "1.40\n"+
                            "1.60\n"+
                            "1.79\n"+
                            "1.80\n"+
                            "2.80\n"+
                            "3.80\n"+
                            "0.21\n"
                            );
               
       
        
    }
    
    public static BlOcParamView getFramePerfil(java.awt.Frame janela){
          if (jFramePerfil == null) {
            jFramePerfil = new BlOcParamView(janela);
        }
        return jFramePerfil;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOcParam = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnCompile = new javax.swing.JButton();
        pnlOcParamInside = new javax.swing.JPanel();
        pnlOcParamValues = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtValores = new javax.swing.JEditorPane();
        txtDescricao = new interfacegrafica.dpa.textfield.TextFieldDPA();
        txtDlServiceCode = new interfacegrafica.dpa.textfield.TextFieldDPA();
        txtOperatorID = new interfacegrafica.dpa.textfield.TextFieldDPA();
        txtDlUpdateStamp = new interfacegrafica.dpa.textfield.TextFieldDPA();
        lblDescricao = new interfacegrafica.dpa.labels.LabelDPA();
        lblOperatorID = new interfacegrafica.dpa.labels.LabelDPA();
        lblDlServiceCode = new interfacegrafica.dpa.labels.LabelDPA();
        lblDlUpdateStamp = new interfacegrafica.dpa.labels.LabelDPA();
        pnlOfertas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtCodigo = new javax.swing.JEditorPane();
        lblTitulo = new interfacegrafica.dpa.labels.LabelTituloDPA();
        pnlLog = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        edtLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        pnlOcParam.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setRollover(true);

        btnCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productsfactory/images/execute.png"))); // NOI18N
        btnCompile.setBorderPainted(false);
        btnCompile.setFocusable(false);
        btnCompile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompileActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCompile);

        pnlOcParamInside.setBackground(new java.awt.Color(255, 255, 255));
        pnlOcParamInside.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true)));

        pnlOcParamValues.setBackground(new java.awt.Color(255, 255, 255));
        pnlOcParamValues.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores (Ex.: 0.00)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jScrollPane1.setHorizontalScrollBar(null);

        edtValores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(153, 204, 255)));
        edtValores.setAutoscrolls(false);
        jScrollPane1.setViewportView(edtValores);

        javax.swing.GroupLayout pnlOcParamValuesLayout = new javax.swing.GroupLayout(pnlOcParamValues);
        pnlOcParamValues.setLayout(pnlOcParamValuesLayout);
        pnlOcParamValuesLayout.setHorizontalGroup(
            pnlOcParamValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOcParamValuesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlOcParamValuesLayout.setVerticalGroup(
            pnlOcParamValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOcParamValuesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblDescricao.setText("Descrição BSR (Retirada do IW)");

        lblOperatorID.setText("Operator ID");

        lblDlServiceCode.setText("DL SERVICE CODE");

        lblDlUpdateStamp.setText("DL UPDATE STAMP");

        pnlOfertas.setBackground(new java.awt.Color(255, 255, 255));
        pnlOfertas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ofertas (SOC_CD)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jScrollPane2.setHorizontalScrollBar(null);

        edtCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(153, 204, 255)));
        edtCodigo.setAutoscrolls(false);
        jScrollPane2.setViewportView(edtCodigo);

        javax.swing.GroupLayout pnlOfertasLayout = new javax.swing.GroupLayout(pnlOfertas);
        pnlOfertas.setLayout(pnlOfertasLayout);
        pnlOfertasLayout.setHorizontalGroup(
            pnlOfertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOfertasLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pnlOfertasLayout.setVerticalGroup(
            pnlOfertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOfertasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitulo.setText("GENERATE BL OC PARAM  (UPDATE)");

        pnlLog.setBackground(new java.awt.Color(255, 255, 255));
        pnlLog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        edtLog.setBackground(new java.awt.Color(0, 0, 0));
        edtLog.setColumns(20);
        edtLog.setForeground(new java.awt.Color(0, 153, 0));
        edtLog.setRows(5);
        jScrollPane3.setViewportView(edtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlOcParamInsideLayout = new javax.swing.GroupLayout(pnlOcParamInside);
        pnlOcParamInside.setLayout(pnlOcParamInsideLayout);
        pnlOcParamInsideLayout.setHorizontalGroup(
            pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOcParamInsideLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlOcParamInsideLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOcParamInsideLayout.createSequentialGroup()
                                .addComponent(pnlOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(pnlOcParamValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(pnlLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlOcParamInsideLayout.createSequentialGroup()
                                .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOperatorID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOperatorID))
                                .addGap(27, 27, 27)
                                .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDlServiceCode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDlServiceCode))
                                .addGap(27, 27, 27)
                                .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDlUpdateStamp)
                                    .addComponent(txtDlUpdateStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlOcParamInsideLayout.setVerticalGroup(
            pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOcParamInsideLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(30, 30, 30)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperatorID)
                    .addComponent(lblDlServiceCode)
                    .addComponent(lblDlUpdateStamp))
                .addGap(7, 7, 7)
                .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDlUpdateStamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDlServiceCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperatorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOcParamInsideLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlOcParamInsideLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlOcParamInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlOcParamValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(814, 814, 814))
        );

        javax.swing.GroupLayout pnlOcParamLayout = new javax.swing.GroupLayout(pnlOcParam);
        pnlOcParam.setLayout(pnlOcParamLayout);
        pnlOcParamLayout.setHorizontalGroup(
            pnlOcParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1323, Short.MAX_VALUE)
            .addGroup(pnlOcParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlOcParamInside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOcParamLayout.setVerticalGroup(
            pnlOcParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOcParamLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1423, Short.MAX_VALUE))
            .addGroup(pnlOcParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlOcParamLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(pnlOcParamInside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlOcParam, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCompileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompileActionPerformed
      this.edtLog.setText("");
      if(this.validaCampos()) {
      
        Fields fields = this.getFields();
        List<String> valores = FieldsUtil.getEdtTextByLine(this.edtValores.getText());
        List<String> ofertas = FieldsUtil.getEdtTextByLine(this.edtCodigo.getText());
        List<BlOcParamModel> blOcList =  new ArrayList<>();
        
      
         //JFile configuration
        JFileChooser  fileChooser = new JFileChooser();  
        fileChooser.setDialogTitle("Selecione o diretório para salvar os arquivos");  
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);  
        fileChooser.setAcceptAllFileFilterUsed(false);
       
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) { 
            try {
              edtLog.append("Iniciando...\n");
              edtLog.append("\n");
              edtLog.append("===================================\n");
              edtLog.append("Testando conexão com o banco de dados...\n");
              edtLog.append("===================================\n");
              Connection con = null;
              con = ConexaoOracle.getInstance().getConnection();
              if(con != null){
                this.PrintLog("Conectado com Sucesso!");
                con.close();
                con = null;
                this.PrintLog("===================================");
                this.PrintLog("\n");
                this.PrintLog("===================================");
                this.PrintLog("Verificando ofertas...");
                this.PrintLog("===================================");
                
                List<BlOcParamModel> offers = Verifyer.verifyOfferBlOcParamExists(ofertas);
                for (BlOcParamModel oferta : offers  ) {
                    this.PrintLog(oferta.getOffer().getSocCD() + " - " + oferta.getOffer().getSocName() + " - " + oferta.getOffer().getStatusOffer());
                    BlOcParamModel bl = new BlOcParamModel();
                    
                    
                }
                
                blOcList = offers;
                this.PrintLog("\n");
                this.PrintLog("===================================");
                this.PrintLog("Verificando Valores:");
                this.PrintLog("===================================");
               
                for (String valoresObj : valores) {
                    if(!valores.contains(","))
                    this.PrintLog(valoresObj + " - OK!");
                }
                
                this.PrintLog("\n");
                
                Path pathOS = Paths.get(fileChooser.getSelectedFile()+"\\"+fields.getDlServiceCode()+fields.getDlUpdateStamp());
                
                /** Directorys and  files Creation begin **
                
                /** Creates the OS Directory **/
                this.PrintLog("Criando diretório: "+pathOS.toString());
                if(ArquivosUtil.createDir(pathOS.toString())){
                    this.PrintLog("Diretório criado com sucesso!");
                }else{ 
                    this.PrintLog("Erro ao criar diretório "+pathOS.toString());
                }
                
                /** Creates the UPDATES Directory **/
                this.PrintLog("Criando SubDiretório: " + pathOS.toString()+"\\UPDATES");
                if(ArquivosUtil.createDir(pathOS.toString()+"\\UPDATES")){
                    this.PrintLog("SubDiretório criado com sucesso!");
                }else{ 
                    this.PrintLog("Erro ao criar SubDiretório "+pathOS.toString()+"\\UPDATES");
                }

                /** Creates the ROLLBACK Directory **/
                this.PrintLog("Criando SubDiretório: " + pathOS.toString()+"\\ROLLBACK");
                if(ArquivosUtil.createDir(pathOS.toString()+"\\ROLLBACK")){
                    this.PrintLog("SubDiretório criado com sucesso!");
                }else{ 
                    this.PrintLog("Erro ao criar SubDiretório "+pathOS.toString()+"\\ROLLBACK");
                }
                
                /** Creates the VALIDATION Directory **/
                this.PrintLog("Criando SubDiretório: " + pathOS.toString()+"\\VALIDATION");
                if(ArquivosUtil.createDir(pathOS.toString()+"\\VALIDATION")){
                    this.PrintLog("SubDiretório criado com sucesso!");
                }else{ 
                    this.PrintLog("Erro ao criar SubDiretório "+pathOS.toString()+"\\VALIDATION");
                }

                /** Creates the LOG Directory **/
                this.PrintLog("Criando SubDiretório: " + pathOS.toString()+"\\LOG");
                if(ArquivosUtil.createDir(pathOS.toString()+"\\LOG")){
                    this.PrintLog("SubDiretório criado com sucesso!");
                }else{ 
                    this.PrintLog("Erro ao criar SubDiretório "+pathOS.toString()+"\\LOG");
                }
                
                
                this.PrintLog("===================================");
                this.PrintLog("Gerar Script Updates...");
                this.PrintLog("===================================");

                String contentUpdate = BlOcParamModel.generateUpdateBlOcParam(offers, valores, fields);
                this.PrintLog(contentUpdate);
                
                this.PrintLog("===================================");
                this.PrintLog("Gerar Scripts de Rolback...");
                this.PrintLog("===================================");
                String contentDelete =  BlOcParamModel.generateRollbackBlOcParam(offers, valores,fields);
                this.PrintLog(contentDelete);
                
                this.PrintLog("===================================");
                this.PrintLog("Gerando Query de Validação...");
                this.PrintLog("===================================");
                String contentSelect =  BlOcParamModel.generateSelectBlOcParam(offers, valores, fields);
                this.PrintLog(contentSelect);
                

                    if(ArquivosUtil.createFile(pathOS.toString()+"\\UPDATES\\"+fields.getOsNumber()+"_UPDATES.sql",contentUpdate) &&
                        ArquivosUtil.createFile(pathOS.toString()+"\\ROLLBACK\\"+fields.getOsNumber()+"_ROLLBACK.sql",contentDelete) &&
                        ArquivosUtil.createFile(pathOS.toString()+"\\VALIDATION\\"+fields.getOsNumber()+"_VALIDATION.sql",contentSelect)){
              
                     this.PrintLog("\n");
                     this.PrintLog("***************************************************************************************************************************");
                     this.PrintLog("***************************************************************************************************************************");
                     this.PrintLog("***                                                                       Processo Finalizado com sucesso!                                                           ***");
                     this.PrintLog("***************************************************************************************************************************");
                     this.PrintLog("***************************************************************************************************************************");
                     ArquivosUtil.createFile(pathOS.toString()+"\\LOG\\"+fields.getOsNumber()+"_LOG.txt",this.edtLog.getText());
                    }
                  
              }else {
                  
                  this.PrintLog("===================================");
                  this.PrintLog("Erro ao conectar ao banco de dados!");
                  this.PrintLog("===================================");
              }
              
      } catch (InterruptedException | SQLException | IOException  ex) {
                try {
                    this.PrintLog(ex.getMessage().toString());
                } catch (InterruptedException ex1) {
                    Logger.getLogger(BlOcParamView.class.getName()).log(Level.SEVERE, null, ex1);
                }
          Logger.getLogger(BlOcParamView.class.getName()).log(Level.SEVERE, null, ex);
                
         
      }
       
     } else {
        System.out.println("No Selection ");
    }
   }
          
}//GEN-LAST:event_btnCompileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompile;
    private javax.swing.JEditorPane edtCodigo;
    private javax.swing.JTextArea edtLog;
    private javax.swing.JEditorPane edtValores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDlServiceCode;
    private javax.swing.JLabel lblDlUpdateStamp;
    private javax.swing.JLabel lblOperatorID;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlOcParam;
    private javax.swing.JPanel pnlOcParamInside;
    private javax.swing.JPanel pnlOcParamValues;
    private javax.swing.JPanel pnlOfertas;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDlServiceCode;
    private javax.swing.JTextField txtDlUpdateStamp;
    private javax.swing.JTextField txtOperatorID;
    // End of variables declaration//GEN-END:variables

    /**
    * Valida os campos necessários
    * para a alteração da senha
    * @return 
    */
    private boolean validaCampos() {
    

        if (this.edtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Oferta(s) são obrigatórias", "Atenção!", 2);
            return false;
        } else if (this.edtValores.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira ao menos um PERFIL!", "Atenção!", 2);
            return false;
        } else if (this.edtValores.getText().contains(",")) {
            JOptionPane.showMessageDialog(this, "Os valores não podem conter vírgula (,)!", "Atenção!", 2);
            return false;
        } else if (this.txtDescricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Descrição é Obrigatória", "Atenção!", 2);
            return false;
        } else if (this.txtDlServiceCode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DL SERVICE CODE é Obrigatório", "Atenção!", 2);
            return false;
        } else if (this.txtOperatorID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "OPERATOR ID é Obrigatório", "Atenção!", 2);
            return false;
        }else if (this.txtDlUpdateStamp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DL UPDATE STAMP é Obrigatório", "Atenção!", 2);
            return false;
        }
        
        return true;
    }
    
    
    private Fields getFields(){
        
        Fields fields = new Fields();
        
        fields.setDlServiceCode(this.txtDlServiceCode.getText());
        fields.setDlUpdateStamp(this.txtDlUpdateStamp.getText());
        fields.setOperatorID(this.txtOperatorID.getText());
        fields.setOsDesc(this.txtDescricao.getText());
        
        return fields;
        
        
    }
    
    public void PrintLog(String textLog) throws InterruptedException{
        
                    edtLog.append(textLog + "\n");
                    edtLog.update(edtLog.getGraphics());
        
   }
}

