/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnviaMail.java
 *
 * Created on Mar 7, 2013, 7:18:35 PM
 */
package productsfactory.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import productsfactory.model.Usuario;
import productsfactory.useful.MailUteis;
import productsfactory.useful.TelaUteis;

/**
 *
 * @author Daniel
 */
public class EnviaMail extends javax.swing.JDialog {

    private static EnviaMail jdialogEnviaMail = null;
    private static Usuario user = null;

    public static EnviaMail getDialogEnviaMail(java.awt.Dialog janela, String destino, Usuario usuario) {

        if (jdialogEnviaMail == null) {
            jdialogEnviaMail = new EnviaMail(janela, true, destino, usuario);

        }
        return jdialogEnviaMail;
    }
    
    public static EnviaMail getDialogEnviaMailFrame(java.awt.Frame janela, String destino, Usuario usuario) {

        if (jdialogEnviaMail == null) {
            jdialogEnviaMail = new EnviaMail(janela, true, destino, usuario);

        }
        return jdialogEnviaMail;
    }
    
    public EnviaMail(java.awt.Frame parent , boolean modal, String destino, Usuario usuario){
        
        super(parent, modal);
        initComponents();
        this.inicializa();
        user =  usuario;
        if (!destino.equals("")) {
            this.tfDestino.setText(destino);
            this.tfDestino.setEditable(false);
        }
    }

    /** Creates new form EnviaMail */
    public EnviaMail(java.awt.Dialog parent, boolean modal, String destino, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.inicializa();
        user = usuario;
        if (!destino.equals("")) {
            this.tfDestino.setText(destino);
            this.tfDestino.setEditable(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEnviarEmail = new interfacegrafica.dpa.panels.PanelDPA();
        lblEnviaEmailHead = new interfacegrafica.dpa.labels.LabelDPA();
        lblDestinatario = new interfacegrafica.dpa.labels.LabelDPA();
        tfDestino = new interfacegrafica.dpa.textfield.TextFieldDPA();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensagem = new interfacegrafica.dpa.textarea.TextAreaDPA();
        lblMensagem = new interfacegrafica.dpa.labels.LabelDPA();
        lblContaEmail = new interfacegrafica.dpa.labels.LabelDPA();
        tfContaEmail = new interfacegrafica.dpa.textfield.TextFieldDPA();
        jpfSenhaEmail = new interfacegrafica.dpa.password.PasswordFieldDPA();
        lblSenhaEmail = new interfacegrafica.dpa.labels.LabelDPA();
        buttonSimplesDPA1 = new interfacegrafica.dpa.buttons.ButtonSimplesDPA();
        lblDestinatario1 = new interfacegrafica.dpa.labels.LabelDPA();
        tfAssunto = new interfacegrafica.dpa.textfield.TextFieldDPA();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Envia Email ");

        lblEnviaEmailHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaoficinamusica/images/mail.jpg"))); // NOI18N
        lblEnviaEmailHead.setText("");

        lblDestinatario.setText("Destino:");

        taMensagem.setColumns(20);
        taMensagem.setRows(5);
        jScrollPane1.setViewportView(taMensagem);

        lblMensagem.setText("Mensagem:");

        lblContaEmail.setText("Conta Email(hotmail):");

        lblSenhaEmail.setText("Senha Email:");

        buttonSimplesDPA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaoficinamusica/images/email_send.png"))); // NOI18N
        buttonSimplesDPA1.setText("Enviar");
        buttonSimplesDPA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimplesDPA1ActionPerformed(evt);
            }
        });

        lblDestinatario1.setText("Assunto:");

        javax.swing.GroupLayout pnlEnviarEmailLayout = new javax.swing.GroupLayout(pnlEnviarEmail);
        pnlEnviarEmail.setLayout(pnlEnviarEmailLayout);
        pnlEnviarEmailLayout.setHorizontalGroup(
            pnlEnviarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnviarEmailLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlEnviarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnviarEmailLayout.createSequentialGroup()
                        .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEnviarEmailLayout.createSequentialGroup()
                        .addComponent(lblDestinatario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEnviarEmailLayout.createSequentialGroup()
                        .addComponent(lblContaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnviarEmailLayout.createSequentialGroup()
                        .addGroup(pnlEnviarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpfSenhaEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(tfContaEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(lblSenhaEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimplesDPA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnviarEmailLayout.createSequentialGroup()
                        .addGroup(pnlEnviarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfAssunto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(tfDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(lblDestinatario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnviaEmailHead, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addGap(30, 30, 30))
        );
        pnlEnviarEmailLayout.setVerticalGroup(
            pnlEnviarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnviarEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnviaEmailHead, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDestinatario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnviarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnviarEmailLayout.createSequentialGroup()
                        .addComponent(tfContaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSenhaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpfSenhaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonSimplesDPA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pnlEnviarEmail, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void buttonSimplesDPA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimplesDPA1ActionPerformed
// TODO add your handling code here:
    if (validaCampos()) {
        if (MailUteis.enviaEmail(this.tfDestino.getText(), this.tfContaEmail.getText(), String.valueOf(this.jpfSenhaEmail.getPassword()),
                this.tfAssunto.getText(), this.taMensagem.getText())) {
            EnviaEmailProgress enviaEmailProgress = new EnviaEmailProgress(this, true);
                        enviaEmailProgress.setVisible(true);
            JOptionPane.showMessageDialog(this, "Email enviado com sucesso!", "Envio de email", 1);
          this.limpaCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Email não pode ser enviado!", "Envio de email", 0);
        }
    }
}//GEN-LAST:event_buttonSimplesDPA1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfacegrafica.dpa.buttons.ButtonSimplesDPA buttonSimplesDPA1;
    private javax.swing.JScrollPane jScrollPane1;
    private interfacegrafica.dpa.password.PasswordFieldDPA jpfSenhaEmail;
    private interfacegrafica.dpa.labels.LabelDPA lblContaEmail;
    private interfacegrafica.dpa.labels.LabelDPA lblDestinatario;
    private interfacegrafica.dpa.labels.LabelDPA lblDestinatario1;
    private interfacegrafica.dpa.labels.LabelDPA lblEnviaEmailHead;
    private interfacegrafica.dpa.labels.LabelDPA lblMensagem;
    private interfacegrafica.dpa.labels.LabelDPA lblSenhaEmail;
    private interfacegrafica.dpa.panels.PanelDPA pnlEnviarEmail;
    private interfacegrafica.dpa.textarea.TextAreaDPA taMensagem;
    private interfacegrafica.dpa.textfield.TextFieldDPA tfAssunto;
    private interfacegrafica.dpa.textfield.TextFieldDPA tfContaEmail;
    private interfacegrafica.dpa.textfield.TextFieldDPA tfDestino;
    // End of variables declaration//GEN-END:variables

    private void addWindowListener() {

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent evt) {
                System.gc();
                jdialogEnviaMail = null;
            }
        });
    }

    
    /**
     * Método utilizado para validar alguns campos 
     * do formulário
     * @return boolean
     */
    private boolean validaCampos() {

        Integer cont = 0;

        if (this.tfDestino.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Destino obrigatório!", "Email", 2);
            cont += 1;
        }

        if (this.tfAssunto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Assunto obrigatório!", "Email", 2);
            cont += 1;
        }

        if (this.tfContaEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Conta de email obrigatória!", "Email", 2);
            cont += 1;
        }

        if (this.taMensagem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mensagem obrigatória!", "Email", 2);
            cont += 1;
        }

        if (String.valueOf(this.jpfSenhaEmail.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(this, "Senha obrigatória!", "Email", 2);
            cont += 1;
        }

        if (cont == 0) {
            return true;
        } else {
            return false;
        }
    }

    private void limpaCampos(){
        
        this.tfAssunto.setText("");
        this.tfContaEmail.setText("");
        this.tfDestino.setText("");
        this.jpfSenhaEmail.setText("");
        this.taMensagem.setText("");
    }
    
    private void inicializa() {

        this.addWindowListener();
        TelaUteis.locateOnScreen(this, 485, 525);

    }
}
