/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnviaEmailProgress.java
 *
 * Created on 05/05/2013, 20:40:54
 */
package productsfactory.view;

import java.awt.Dimension;

/**
 *
 * @author Daniel
 */
public class EnviaEmailProgress extends javax.swing.JDialog {

    /** Creates new form EnviaEmailProgress */
    public EnviaEmailProgress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializa();
    }
    
    /** Creates new form EnviaEmailProgress */
    public EnviaEmailProgress(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializa();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEnviaEmailProgress = new javax.swing.JPanel();
        lblPath = new javax.swing.JLabel();
        lblPath1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enviando Email");
        setUndecorated(true);

        pnlEnviaEmailProgress.setBackground(new java.awt.Color(255, 255, 255));
        pnlEnviaEmailProgress.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true)));

        lblPath.setText("Enviando Email");

        pgrbrStatus.setForeground(new java.awt.Color(102, 255, 102));
        pgrbrStatus.setMaximum(10);
        pgrbrStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pgrbrStatus.setStringPainted(true);

        lblPath1.setText("Aguarde a confirmação!");

        javax.swing.GroupLayout pnlEnviaEmailProgressLayout = new javax.swing.GroupLayout(pnlEnviaEmailProgress);
        pnlEnviaEmailProgress.setLayout(pnlEnviaEmailProgressLayout);
        pnlEnviaEmailProgressLayout.setHorizontalGroup(
            pnlEnviaEmailProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnviaEmailProgressLayout.createSequentialGroup()
                .addGroup(pnlEnviaEmailProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnviaEmailProgressLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblPath))
                    .addGroup(pnlEnviaEmailProgressLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlEnviaEmailProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEnviaEmailProgressLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblPath1))
                            .addComponent(pgrbrStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlEnviaEmailProgressLayout.setVerticalGroup(
            pnlEnviaEmailProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnviaEmailProgressLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgrbrStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPath1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEnviaEmailProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEnviaEmailProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblPath1;
    private final javax.swing.JProgressBar pgrbrStatus = new javax.swing.JProgressBar();
    private javax.swing.JPanel pnlEnviaEmailProgress;
    // End of variables declaration//GEN-END:variables
private void locateOnScreen() {
        final Dimension paneSize = this.getSize();
        final Dimension screenSize = this.getToolkit().getScreenSize();
        this.setLocation((screenSize.width - paneSize.width) / 2,
                (screenSize.height - paneSize.height) / 2);
}



public void rodaProgress() {

        new Thread(new Runnable() {

            public void run() {
                for (int i = 1; i <= 30; i++) {
                    pgrbrStatus.setValue(i);
                    if(i == 30){
                       dispose(); 
                     
                    }
                    try {
                        Thread.sleep(100);  
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
}
public void inicializa() {

        this.setSize(228, 115);
        this.locateOnScreen();
        this.rodaProgress();

    }



}
