/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogPontoFuncionario.java
 *
 * Created on 14/04/2013, 00:29:06
 */
package productsfactory.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import productsfactory.control.UsuarioControl;
import productsfactory.model.AcoesUsuarios;
import productsfactory.model.Usuario;
import productsfactory.tables.TableAcoesUsuario;
import productsfactory.useful.TelaUteis;

/**
 *
 * @author Daniel
 */
public class LogAcoesUsuario extends javax.swing.JDialog {

    private static Usuario user;
    private static LogAcoesUsuario jDialogLogAcesso = null;

    public static LogAcoesUsuario getDialogLogAcoes(java.awt.Frame janela, Usuario usuario) throws SQLException {

        if (jDialogLogAcesso == null) {
            jDialogLogAcesso = new LogAcoesUsuario(janela, true, usuario);
        }
        return jDialogLogAcesso;
    }

    /** Creates new form LogPontoFuncionario */
    public LogAcoesUsuario(java.awt.Frame parent, boolean modal, Usuario usuario) throws SQLException {
        super(parent, modal);
        initComponents();
        this.inicializa();
        user = usuario;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAcoesUsuario = new interfacegrafica.dpa.panels.PanelDPA();
        lblUsuario = new interfacegrafica.dpa.labels.LabelDPA();
        lblDataInicio = new interfacegrafica.dpa.labels.LabelDPA();
        dtDataInicio = new com.toedter.calendar.JDateChooser();
        lblDataTermino = new interfacegrafica.dpa.labels.LabelDPA();
        dtDataTermino = new com.toedter.calendar.JDateChooser();
        btnConsultar = new interfacegrafica.dpa.buttons.ButtonSimplesDPA();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcoesUsuario = new javax.swing.JTable();
        lblLogAcessoHead = new interfacegrafica.dpa.labels.LabelDPA();
        cmbUsuario = new interfacegrafica.dpa.combobox.ComboboxAutoCompleteDPA();
        tfFiltro = new interfacegrafica.dpa.textfield.TextFieldDPA();
        lblFiltro = new interfacegrafica.dpa.labels.LabelDPA();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log Ações do Usuário");
        setResizable(false);

        lblUsuario.setText("Usuário:");

        lblDataInicio.setText("Data Início:");

        lblDataTermino.setText("Data Término:");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaoficinamusica/images/search_little.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        tblAcoesUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAcoesUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAcoesUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAcoesUsuario);

        lblLogAcessoHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaoficinamusica/images/logacoesusuario.jpg"))); // NOI18N
        lblLogAcessoHead.setText("");

        tfFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFiltroKeyPressed(evt);
            }
        });

        lblFiltro.setText("Palavra(Filtro):");

        javax.swing.GroupLayout pnlAcoesUsuarioLayout = new javax.swing.GroupLayout(pnlAcoesUsuario);
        pnlAcoesUsuario.setLayout(pnlAcoesUsuarioLayout);
        pnlAcoesUsuarioLayout.setHorizontalGroup(
            pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesUsuarioLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAcoesUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAcoesUsuarioLayout.createSequentialGroup()
                                .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlAcoesUsuarioLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(lblLogAcessoHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        pnlAcoesUsuarioLayout.setVerticalGroup(
            pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesUsuarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblLogAcessoHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAcoesUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAcoesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAcoesUsuarioLayout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(pnlAcoesUsuario, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
// TODO add your handling code here:
//    if (this.dtDataInicio.getDate() != null && this.dtDataTermino.getDate() != null) {
//        try {
//            Usuario usuario = (Usuario) this.cmbUsuario.getSelectedItem();
//
//
//            List<AcoesUsuarios> listAcoes = PontoFuncionarioControl.listaAcoes(this.dtDataInicio.getDate(), this.dtDataTermino.getDate(),
//                    usuario, this.tfFiltro.getText());
//            this.tableAcoesUsuario(listAcoes);
//        } catch (SQLException ex) {
//            Logger.getLogger(LogAcoesUsuario.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    } else {
//        JOptionPane.showMessageDialog(this, "Preencha os campos para a pesquisa.", "Atençao", 2);
//    }
}//GEN-LAST:event_btnConsultarActionPerformed

private void tblAcoesUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAcoesUsuarioMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 1) {

        JOptionPane.showMessageDialog(this, "Usuário: " + tblAcoesUsuario.getValueAt(tblAcoesUsuario.getSelectedRow(), 5) + "\r\n"
                + "Descrição : " + tblAcoesUsuario.getValueAt(tblAcoesUsuario.getSelectedRow(), 1) + "\r\n"
                + "Data : " + tblAcoesUsuario.getValueAt(tblAcoesUsuario.getSelectedRow(), 2) + "\r\n"
                + "Hora : " + tblAcoesUsuario.getValueAt(tblAcoesUsuario.getSelectedRow(), 3) + "", "Detalhes", 1);
    }
}//GEN-LAST:event_tblAcoesUsuarioMouseClicked

private void tfFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroKeyPressed
// TODO add your handling code here:

//    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//        if (this.dtDataInicio.getDate() != null && this.dtDataTermino.getDate() != null) {
//            try {
//                Usuario usuario = (Usuario) this.cmbUsuario.getSelectedItem();
//
//
//                List<AcoesUsuarios> listAcoes = PontoFuncionarioControl.listaAcoes(this.dtDataInicio.getDate(), this.dtDataTermino.getDate(),
//                        usuario, this.tfFiltro.getText());
//                this.tableAcoesUsuario(listAcoes);
//            } catch (SQLException ex) {
//                Logger.getLogger(LogAcoesUsuario.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Preencha os campos para a pesquisa.", "Atençao", 2);
//        }
//
//    }
}//GEN-LAST:event_tfFiltroKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfacegrafica.dpa.buttons.ButtonSimplesDPA btnConsultar;
    private interfacegrafica.dpa.combobox.ComboboxAutoCompleteDPA cmbUsuario;
    private com.toedter.calendar.JDateChooser dtDataInicio;
    private com.toedter.calendar.JDateChooser dtDataTermino;
    private javax.swing.JScrollPane jScrollPane1;
    private interfacegrafica.dpa.labels.LabelDPA lblDataInicio;
    private interfacegrafica.dpa.labels.LabelDPA lblDataTermino;
    private interfacegrafica.dpa.labels.LabelDPA lblFiltro;
    private interfacegrafica.dpa.labels.LabelDPA lblLogAcessoHead;
    private interfacegrafica.dpa.labels.LabelDPA lblUsuario;
    private interfacegrafica.dpa.panels.PanelDPA pnlAcoesUsuario;
    private javax.swing.JTable tblAcoesUsuario;
    private interfacegrafica.dpa.textfield.TextFieldDPA tfFiltro;
    // End of variables declaration//GEN-END:variables

    private JTable tableAcoesUsuario(List<AcoesUsuarios> listAcoesUsuario) throws SQLException {


        TableAcoesUsuario model = new TableAcoesUsuario();
        // table header
        JTableHeader th = tblAcoesUsuario.getTableHeader();
        th.setFont(new Font("Arial", Font.BOLD, 13));
        th.setBackground(new Color(185, 211, 238));

        tblAcoesUsuario.setModel(model);

        tblAcoesUsuario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        tblAcoesUsuario.getColumnModel().getColumn(0).setMinWidth(0);
        tblAcoesUsuario.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblAcoesUsuario.getColumnModel().getColumn(0).setMaxWidth(0);

        //tblAcoesUsuario.getColumnModel().getColumn(1).setMinWidth(500);
        tblAcoesUsuario.getColumnModel().getColumn(1).setPreferredWidth(500);
        //tblAcoesUsuario.getColumnModel().getColumn(1).setMaxWidth(800);
        tblAcoesUsuario.getColumnModel().getColumn(1).setResizable(true);

        tblAcoesUsuario.getColumnModel().getColumn(2).setMinWidth(250);
        tblAcoesUsuario.getColumnModel().getColumn(2).setPreferredWidth(250);
        tblAcoesUsuario.getColumnModel().getColumn(2).setMaxWidth(250);

        tblAcoesUsuario.getColumnModel().getColumn(3).setMinWidth(80);
        tblAcoesUsuario.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblAcoesUsuario.getColumnModel().getColumn(3).setMaxWidth(80);

        tblAcoesUsuario.getColumnModel().getColumn(4).setMinWidth(0);
        tblAcoesUsuario.getColumnModel().getColumn(4).setPreferredWidth(0);
        tblAcoesUsuario.getColumnModel().getColumn(4).setMaxWidth(0);

        tblAcoesUsuario.getColumnModel().getColumn(5).setMinWidth(0);
        tblAcoesUsuario.getColumnModel().getColumn(5).setPreferredWidth(0);
        tblAcoesUsuario.getColumnModel().getColumn(5).setMaxWidth(0);



        //TableColumn col1 = tblAcoesUsuario.getColumnModel().getColumn(1);
        TableColumn col2 = tblAcoesUsuario.getColumnModel().getColumn(2);
        TableColumn col3 = tblAcoesUsuario.getColumnModel().getColumn(3);



        DefaultTableCellRenderer cAlign = new DefaultTableCellRenderer();

        cAlign.setHorizontalAlignment(JLabel.CENTER);
        //col1.setCellRenderer(cAlign);
        col2.setCellRenderer(cAlign);
        col3.setCellRenderer(cAlign);

        model.setAcoes(listAcoesUsuario);
        return tblAcoesUsuario;
    }

    private void populaComboUsuario() throws SQLException {

        //assim como é feito numa JTable, temos o DefaultComboBoxModel que é o model do JComboBox
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) this.cmbUsuario.getModel();
        //removendo todos os elementos do combo
        comboModel.removeAllElements();
        //cria a lista: java.util.List
        List<Usuario> usuario = new ArrayList<Usuario>();

        usuario = UsuarioControl.ComboUsuarios();

        if (usuario != null) {

            for (int i = 0; i <= usuario.size() - 1; i++) {
                Usuario userCombo = usuario.get(i);
                comboModel.addElement(userCombo);
            }
        }


    }

    private void addWindowListener() {

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent evt) {
                System.gc();
                jDialogLogAcesso = null;
            }
        });
    }

    private void inicializa() throws SQLException {
        this.addWindowListener();
        this.populaComboUsuario();
        TelaUteis.locateOnScreen(this, 1000, 530);

    }
}
