/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TarefasView.java
 *
 * Created on 13/04/2013, 16:46:30
 */
package productsfactory.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import productsfactory.control.TarefasControl;
import productsfactory.control.UsuarioControl;
import productsfactory.model.Tarefa;
import productsfactory.model.Usuario;
import productsfactory.tables.TableTarefas;
import productsfactory.useful.DataUteis;
import productsfactory.useful.TelaUteis;

/**
 *
 * @author Daniel
 */
public class TarefasView extends javax.swing.JDialog {

    private static Usuario user = null;
    private Integer codigoTarefa = null;
    private String usuarioDono = null;
    private static TarefasView jDialogTarefasView = null;

    public static TarefasView getDialogTarefas(java.awt.Frame janela, Usuario usuario) throws SQLException {

        if (jDialogTarefasView == null) {
            jDialogTarefasView = new TarefasView(janela, true, usuario);
        }
        return jDialogTarefasView;
    }

    /** Creates new form TarefasView */
    public TarefasView(java.awt.Frame parent, boolean modal, Usuario usuario) throws SQLException {
        super(parent, modal);
        initComponents();
        user = usuario;
        this.inicializa();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTarefas = new interfacegrafica.dpa.panels.PanelDPA();
        lblTarefasHead = new interfacegrafica.dpa.labels.LabelDPA();
        pnlCadastroTarefas = new interfacegrafica.dpa.panels.PanelTituloDPA("Tarefa");
        lblDescricaoTarefa = new interfacegrafica.dpa.labels.LabelDPA();
        lblStatusTarefa = new interfacegrafica.dpa.labels.LabelDPA();
        lblHoraTarefa = new interfacegrafica.dpa.labels.LabelDPA();
        lblDataTarefa = new interfacegrafica.dpa.labels.LabelDPA();
        tfDescricaTarefa = new interfacegrafica.dpa.textfield.TextFieldDPA();
        cmbStatusTarefa = new interfacegrafica.dpa.combobox.ComboboxDPA();
        ftfHoraTarefa = new interfacegrafica.dpa.jformatedtextfield.JFormattedHoraMinutoDPA();
        dtDataTarefa = new com.toedter.calendar.JDateChooser();
        cmbUsuario = new interfacegrafica.dpa.combobox.ComboboxDPA();
        lblUsuario = new interfacegrafica.dpa.labels.LabelDPA();
        btnLimpar = new interfacegrafica.dpa.buttons.ButtonLimparDPA();
        btnSalvar = new interfacegrafica.dpa.buttons.ButtonSalvarDPA();
        btnAtualizar = new interfacegrafica.dpa.buttons.ButtonAtualizarDPA();
        btnExcluir = new interfacegrafica.dpa.buttons.ButtonExcluirDPA();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarefas = new javax.swing.JTable();
        dtDataInicio = new com.toedter.calendar.JDateChooser();
        dtDataTermino = new com.toedter.calendar.JDateChooser();
        btnFiltrar = new interfacegrafica.dpa.buttons.ButtonSimplesDPA();
        lblDataTermino = new interfacegrafica.dpa.labels.LabelDPA();
        lblDataInicio = new interfacegrafica.dpa.labels.LabelDPA();
        lblHelp = new interfacegrafica.dpa.labels.LabelDPA();
        lblStatusTarefa1 = new interfacegrafica.dpa.labels.LabelDPA();
        cmbStatusTarefaConsulta = new interfacegrafica.dpa.combobox.ComboboxDPA();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tarefas");
        setResizable(false);

        lblTarefasHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productsfactory/images/tarefas.jpg"))); // NOI18N
        lblTarefasHead.setText("");

        lblDescricaoTarefa.setText("Descrição Tarefa:");

        lblStatusTarefa.setText("Status Tarefa:");

        lblHoraTarefa.setText("Hora Tarefa:");

        lblDataTarefa.setText("Data Tarefa:");

        cmbStatusTarefa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativa", "Inativa", "Concluída" }));

        ftfHoraTarefa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblUsuario.setText("Usuário (atribuir tarefa):");

        javax.swing.GroupLayout pnlCadastroTarefasLayout = new javax.swing.GroupLayout(pnlCadastroTarefas);
        pnlCadastroTarefas.setLayout(pnlCadastroTarefasLayout);
        pnlCadastroTarefasLayout.setHorizontalGroup(
            pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroTarefasLayout.createSequentialGroup()
                        .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDescricaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatusTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCadastroTarefasLayout.createSequentialGroup()
                        .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ftfHoraTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHoraTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtDataTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlCadastroTarefasLayout.setVerticalGroup(
            pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCadastroTarefasLayout.createSequentialGroup()
                        .addComponent(lblDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDescricaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroTarefasLayout.createSequentialGroup()
                        .addComponent(lblStatusTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStatusTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroTarefasLayout.createSequentialGroup()
                        .addComponent(lblHoraTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(ftfHoraTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroTarefasLayout.createSequentialGroup()
                        .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCadastroTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dtDataTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpar.setText("");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTarefasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTarefas);

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productsfactory/images/search_little.png"))); // NOI18N
        btnFiltrar.setText("Filtrar/Data");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        lblDataTermino.setText("Data Término");

        lblDataInicio.setText("Data Início:");

        lblHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productsfactory/images/help.png"))); // NOI18N
        lblHelp.setText("");
        lblHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHelpMouseClicked(evt);
            }
        });

        lblStatusTarefa1.setText("Status Tarefa:");

        cmbStatusTarefaConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativa", "Inativa", "Concluída" }));
        cmbStatusTarefaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusTarefaConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTarefasLayout = new javax.swing.GroupLayout(pnlTarefas);
        pnlTarefas.setLayout(pnlTarefasLayout);
        pnlTarefasLayout.setHorizontalGroup(
            pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarefasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTarefasLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarefasLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTarefasLayout.createSequentialGroup()
                                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatusTarefa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatusTarefaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnlCadastroTarefas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125))
                    .addGroup(pnlTarefasLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(lblTarefasHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335)
                        .addComponent(lblHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarefasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        pnlTarefasLayout.setVerticalGroup(
            pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTarefasLayout.createSequentialGroup()
                        .addComponent(lblTarefasHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCadastroTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTarefasLayout.createSequentialGroup()
                                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnFiltrar, 0, 0, Short.MAX_VALUE)
                                    .addComponent(dtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlTarefasLayout.createSequentialGroup()
                                .addComponent(lblStatusTarefa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbStatusTarefaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        getContentPane().add(pnlTarefas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
// TODO add your handling code here:
    this.limpaCampos();
}//GEN-LAST:event_btnLimparActionPerformed

private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
// TODO add your handling code here:
    if (this.validaCampos()) {

        if (TarefasControl.inserirTarefa(this.getDataTarefa())) {
            JOptionPane.showMessageDialog(this, "Tarefa Inserida com sucesso", "Tarefas", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Tarefa não pode ser inserida.", "Tarefas", 0);
        }
    }

}//GEN-LAST:event_btnSalvarActionPerformed

private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
// TODO add your handling code here:
    if (this.validaCampos()) {
        int option = JOptionPane.showConfirmDialog(this, "Confirma atualização?", "Tarefas", JOptionPane.YES_NO_OPTION, 3);

        if (option == 0) {

           
            if (TarefasControl.atualizarTarefa(this.getDataTarefa())) {
                try {
                    List<Tarefa> listTarefas = TarefasControl.listaTarefasData(this.dtDataInicio.getDate(), this.dtDataTermino.getDate(), user);
                    tableTarefas(listTarefas);
                    JOptionPane.showMessageDialog(this, "Tarefa Atualizada com sucesso", "Tarefas", 1);
                    //ControleUsuario.insereAcoesUsuario("Atualizou a tarefa : " + this.tfDescricaTarefa.getText() + "", user);
                } catch (SQLException ex) {
                    Logger.getLogger(TarefasView.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tarefa não pode ser atualizada.", "Tarefas", 0);
            }
        }
    }


}//GEN-LAST:event_btnAtualizarActionPerformed

private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
// TODO add your handling code here:
    if (user.getNomeUsuario().equals(usuarioDono)) {
       
            int option = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir essa tarefa?", "Tarefas", JOptionPane.YES_NO_OPTION, 3);

            if (option == 0) {
                 if (TarefasControl.excluirTarefa(this.getDataTarefa())) {

                try {
                    JOptionPane.showMessageDialog(this, "Tarefa excluída com sucesso!", "Tarefas", 1);
                   // ControleUsuario.insereAcoesUsuario("Excluiu a tarefa : " + this.tfDescricaTarefa.getText() + "", user);
                    this.limpaCampos();
                    List<Tarefa> listTarefas = null;
                    this.tableTarefas(listTarefas);
                } catch (SQLException ex) {
                    Logger.getLogger(TarefasView.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tarefa não pode ser excluída!", "Tarefas", 0);
            }

        } else {
             JOptionPane.showMessageDialog(this, "Exclusão cancelada pelo usuário.", "Tarefas", 1);
           
            
        }
    } else {
        JOptionPane.showMessageDialog(this, "Somente o usuário que criou essa tarefa poderá fazer sua exclusão.", "Tarefas", 1);
    }

}//GEN-LAST:event_btnExcluirActionPerformed

private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
// TODO add your handling code here:
    if (this.dtDataInicio.getDate() != null && this.dtDataTermino.getDate() != null) {
        try {
            List<Tarefa> listTarefas = TarefasControl.listaTarefasData(this.dtDataInicio.getDate(), this.dtDataTermino.getDate(), user);
            tableTarefas(listTarefas);
        } catch (SQLException ex) {
            Logger.getLogger(TarefasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Preencha os campos para pesquisa", "Tarefas", 2);
    }
}//GEN-LAST:event_btnFiltrarActionPerformed

private void tblTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTarefasMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 1) {

        codigoTarefa = Integer.valueOf(tblTarefas.getValueAt(tblTarefas.getSelectedRow(), 0).toString());
        this.tfDescricaTarefa.setText(tblTarefas.getValueAt(tblTarefas.getSelectedRow(), 1).toString());
        this.dtDataTarefa.setDate(DataUteis.sdfParse(tblTarefas.getValueAt(tblTarefas.getSelectedRow(), 2).toString()));
        this.ftfHoraTarefa.setText(tblTarefas.getValueAt(tblTarefas.getSelectedRow(), 3).toString());
        this.cmbStatusTarefa.setSelectedItem(tblTarefas.getValueAt(tblTarefas.getSelectedRow(), 4).toString());
        usuarioDono = tblTarefas.getValueAt(tblTarefas.getSelectedRow(), 5).toString();
        //testando valor da comboCargo
        for (int index = 0; index < cmbUsuario.getItemCount(); index++) {
            if (cmbUsuario.getItemAt(index).toString().equals(tblTarefas.getValueAt(tblTarefas.getSelectedRow(), 6).toString())) {
                cmbUsuario.setSelectedIndex(index);
                break;
            }
        }
        if(!user.getNomeUsuario().equals(usuarioDono)){
            
            this.tfDescricaTarefa.setEditable(false);
            this.ftfHoraTarefa.setEditable(false);
            this.dtDataTarefa.setEnabled(false);
            this.cmbUsuario.setEnabled(false);
            
        }else{
            
            this.tfDescricaTarefa.setEditable(true);
            this.ftfHoraTarefa.setEditable(true);
            this.dtDataTarefa.setEnabled(true);
            this.cmbUsuario.setEnabled(true);
        }
        this.btnAtualizar.setVisible(true);
        this.btnExcluir.setVisible(true);
        this.btnSalvar.setVisible(false);


    }
}//GEN-LAST:event_tblTarefasMouseClicked

private void lblHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHelpMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 1) {
        JOptionPane.showMessageDialog(this, "Para cadastrar uma tarefa escolha uam descrição,o status\n\r"
                + "a data e a hora, escolha o usuário que será responsável pela\n\r"
                + "execução da tarefa. Obs: Somente os usuários envolvidos na tarefa\n\r"
                + "terão acesso as informações.", "Help - Tarefas", 1);
    }
}//GEN-LAST:event_lblHelpMouseClicked

private void cmbStatusTarefaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusTarefaConsultaActionPerformed
// TODO add your handling code here:
    if (this.dtDataInicio.getDate() != null && this.dtDataTermino.getDate() != null) {
        try {
            List<Tarefa> listTarefas = TarefasControl.listaTarefasStatus(this.dtDataInicio.getDate(), this.dtDataTermino.getDate(),
                    this.cmbStatusTarefaConsulta.getSelectedItem().toString(), user);
            tableTarefas(listTarefas);
        } catch (SQLException ex) {
            Logger.getLogger(TarefasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Preencha os campos para pesquisa", "Tarefas", 2);
    }
}//GEN-LAST:event_cmbStatusTarefaConsultaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfacegrafica.dpa.buttons.ButtonAtualizarDPA btnAtualizar;
    private interfacegrafica.dpa.buttons.ButtonExcluirDPA btnExcluir;
    private interfacegrafica.dpa.buttons.ButtonSimplesDPA btnFiltrar;
    private interfacegrafica.dpa.buttons.ButtonLimparDPA btnLimpar;
    private interfacegrafica.dpa.buttons.ButtonSalvarDPA btnSalvar;
    private interfacegrafica.dpa.combobox.ComboboxDPA cmbStatusTarefa;
    private interfacegrafica.dpa.combobox.ComboboxDPA cmbStatusTarefaConsulta;
    private interfacegrafica.dpa.combobox.ComboboxDPA cmbUsuario;
    private com.toedter.calendar.JDateChooser dtDataInicio;
    private com.toedter.calendar.JDateChooser dtDataTarefa;
    private com.toedter.calendar.JDateChooser dtDataTermino;
    private interfacegrafica.dpa.jformatedtextfield.JFormattedHoraMinutoDPA ftfHoraTarefa;
    private javax.swing.JScrollPane jScrollPane1;
    private interfacegrafica.dpa.labels.LabelDPA lblDataInicio;
    private interfacegrafica.dpa.labels.LabelDPA lblDataTarefa;
    private interfacegrafica.dpa.labels.LabelDPA lblDataTermino;
    private interfacegrafica.dpa.labels.LabelDPA lblDescricaoTarefa;
    private interfacegrafica.dpa.labels.LabelDPA lblHelp;
    private interfacegrafica.dpa.labels.LabelDPA lblHoraTarefa;
    private interfacegrafica.dpa.labels.LabelDPA lblStatusTarefa;
    private interfacegrafica.dpa.labels.LabelDPA lblStatusTarefa1;
    private interfacegrafica.dpa.labels.LabelDPA lblTarefasHead;
    private interfacegrafica.dpa.labels.LabelDPA lblUsuario;
    private interfacegrafica.dpa.panels.PanelTituloDPA pnlCadastroTarefas;
    private interfacegrafica.dpa.panels.PanelDPA pnlTarefas;
    private javax.swing.JTable tblTarefas;
    private interfacegrafica.dpa.textfield.TextFieldDPA tfDescricaTarefa;
    // End of variables declaration//GEN-END:variables

    private JTable tableTarefas(List<Tarefa> listTarefa) throws SQLException {


        TableTarefas model = new TableTarefas();
        // table header
        JTableHeader th = tblTarefas.getTableHeader();
        th.setFont(new Font("Arial", Font.BOLD, 13));
        th.setBackground(new Color(185, 211, 238));

        tblTarefas.setModel(model);

        tblTarefas.getColumnModel().getColumn(0).setMinWidth(0);
        tblTarefas.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblTarefas.getColumnModel().getColumn(0).setMaxWidth(0);

        tblTarefas.getColumnModel().getColumn(1).setMinWidth(300);
        tblTarefas.getColumnModel().getColumn(1).setPreferredWidth(300);
        tblTarefas.getColumnModel().getColumn(1).setMaxWidth(300);

        tblTarefas.getColumnModel().getColumn(2).setMinWidth(90);
        tblTarefas.getColumnModel().getColumn(2).setPreferredWidth(90);
        tblTarefas.getColumnModel().getColumn(2).setMaxWidth(90);

        tblTarefas.getColumnModel().getColumn(3).setMinWidth(80);
        tblTarefas.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblTarefas.getColumnModel().getColumn(3).setMaxWidth(80);

        tblTarefas.getColumnModel().getColumn(4).setMinWidth(120);
        tblTarefas.getColumnModel().getColumn(4).setPreferredWidth(120);
        tblTarefas.getColumnModel().getColumn(4).setMaxWidth(120);

        tblTarefas.getColumnModel().getColumn(5).setMinWidth(110);
        tblTarefas.getColumnModel().getColumn(5).setPreferredWidth(100);
        tblTarefas.getColumnModel().getColumn(5).setMaxWidth(110);

        tblTarefas.getColumnModel().getColumn(6).setMinWidth(140);
        tblTarefas.getColumnModel().getColumn(6).setPreferredWidth(140);
        tblTarefas.getColumnModel().getColumn(6).setMaxWidth(140);



        TableColumn col2 = tblTarefas.getColumnModel().getColumn(2);
        TableColumn col3 = tblTarefas.getColumnModel().getColumn(3);
        TableColumn col4 = tblTarefas.getColumnModel().getColumn(4);



        DefaultTableCellRenderer cAlign = new DefaultTableCellRenderer();

        cAlign.setHorizontalAlignment(JLabel.CENTER);
        col2.setCellRenderer(cAlign);
        col3.setCellRenderer(cAlign);
        col4.setCellRenderer(cAlign);

        model.setLancamentos(listTarefa);
        return tblTarefas;
    }

    private Tarefa getDataTarefa() {

        Tarefa tarefa = new Tarefa();
        tarefa.setCodigoTarefa(codigoTarefa);
        tarefa.setDataTarefa(this.dtDataTarefa.getDate());
        tarefa.setDescricaoTarefa(this.tfDescricaTarefa.getText());
        tarefa.setHoraTarefa(this.ftfHoraTarefa.getText());
        tarefa.setStatusTarefa(this.cmbStatusTarefa.getSelectedItem().toString());
        Usuario usuario = new Usuario();
        usuario.setNomeUsuario(this.cmbUsuario.getSelectedItem().toString());
        tarefa.setUsuario(usuario);
        tarefa.setDonoTarefa(user.getNomeUsuario());

        return tarefa;
    }

    private void limpaCampos() {

        this.tfDescricaTarefa.setText("");
        this.dtDataTarefa.setDate(null);
        this.ftfHoraTarefa.setText("");
        this.cmbStatusTarefa.setSelectedItem("Ativa");

        this.btnAtualizar.setVisible(false);
        this.btnExcluir.setVisible(false);
        this.btnSalvar.setVisible(true);
    }

    /**
     * Método utilizado para validar alguns campos 
     * do formulário
     * @return boolean
     */
    private boolean validaCampos() {

        Integer cont = 0;

        if (this.tfDescricaTarefa.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Descrição da tarefa obrigatória!", "Tarefas", 2);
            cont += 1;
        }

        if (this.dtDataTarefa.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Data data tarefa obrigatória!", "Tarefas", 2);
            cont += 1;
        }

        if (this.ftfHoraTarefa.getText().equals("__:__")) {
            JOptionPane.showMessageDialog(this, "Valor da despesa inválido!", "Tarefas", 2);
            cont += 1;
        }


        if (cont == 0) {
            return true;
        } else {
            return false;
        }
    }

    private void populaComboUsuario() throws SQLException {

        //assim como é feito numa JTable, temos o DefaultComboBoxModel que é o model do JComboBox
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) this.cmbUsuario.getModel();
        //removendo todos os elementos do combo
        comboModel.removeAllElements();
        //cria a lista: java.util.List
        List<Usuario> usuario = new ArrayList<Usuario>();

        usuario = UsuarioControl.ComboUsuariosTarefa();

        if (usuario != null) {

            for (int i = 0; i <= usuario.size() - 1; i++) {
                Usuario userCombo = usuario.get(i);
                comboModel.addElement(userCombo);
            }
        }


    }

    private void addWindowListener() {

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent evt) {

                System.gc();
                jDialogTarefasView = null;

            }
        });
    }

    private void inicializa() throws SQLException {
        this.limpaCampos();
        this.addWindowListener();
        this.populaComboUsuario();
        List<Tarefa> listTarefas = TarefasControl.listaTarefasData(new Date(), new Date(), user);
        tableTarefas(listTarefas);
        TelaUteis.locateOnScreen(this, 992, 680);
    }
}
