/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelatorioAlunosAtivosInativos.java
 *
 * Created on 18/04/2013, 21:49:43
 */
package productsfactory.relatorios;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import productsfactory.useful.TelaUteis;

/**
 *
 * @author Daniel
 */
public class RelatorioPagamentoFuncionarios extends javax.swing.JDialog {
    private static RelatorioPagamentoFuncionarios jDialogReport = null;

    public static RelatorioPagamentoFuncionarios getDialogReport(java.awt.Dialog janela,boolean modal) {

        if (jDialogReport == null) {
            jDialogReport = new RelatorioPagamentoFuncionarios(janela, modal);
        }
        return jDialogReport;
    }
    /** Creates new form RelatorioAlunosAtivosInativos */
    public RelatorioPagamentoFuncionarios(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializa();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


private void addWindowListener() {

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent evt) {
                System.gc();
                jDialogReport = null;
            }
        });
    }


private void inicializa(){
    addWindowListener();
    TelaUteis.locateOnScreen(this, 1024, 768);
}
}
